#ifndef __3941_PIN_DEF
#define __3941_PIN_DEF

#define DRIVE_FRONTLEFT 1
#define DRIVE_REARLEFT 2
#define DRIVE_FRONTRIGHT 3
#define DRIVE_REARRIGHT 4
#define DRIVE_LEFTENCODERA 11
#define DRIVE_LEFTENCODERB 12

#define PRESSURESWITCH_PIN 6
#define COMPRELAY_PIN 1

#define DRIVE_SUPERSHIFTSOLIN 7
#define DRIVE_SUPERSHIFTSOLOUT 8

#define SHOOTER_WINCH_SPIKE 5
#define SHOOTER_WINCHDIGITALENCA 1
#define SHOOTER_WINCHDIGITALENCB 1
#define SHOOTER_WINCHMOTORSOLIN 3
#define SHOOTER_WINCHMOTORSOLOUT 4
#define SHOOTER_WINCHRATCHSOLIN 6
#define SHOOTER_WINCHRATCHSOLOUT 5
#define SHOOTER_WINCHLIMITSWITCH 7
#define SHOOTER_ARMTALON 6
#define SHOOTER_ARMLIMITSWITCHBACK 9
#define SHOOTER_ARMLIMITSWITCHFRONT 8
#define SHOOTER_ARMPOT 8

#define PICKUP_ROLLERSPIKE 4
#define PICKUP_PICKUPARMSOLIN 1
#define PICKUP_PICKUPARMSOLOUT 2

#endif
