#ifndef __3941_PIN_DEF
#define __3941_PIN_DEF

#define DRIVE_FRONTLEFT 1
#define DRIVE_REARLEFT 2
#define DRIVE_FRONTRIGHT 3
#define DRIVE_REARRIGHT 4

#define PRESSURESWITCH_PIN 1
#define COMPRELAY_PIN 1

#define DRIVE_LEFTSHIFTSOL1 1
#define DRIVE_LEFTSHIFTSOL2 2
#define DRIVE_RIGHTSHIFTSOL1 3
#define DRIVE_RIGHTSHIFTSOL2 4

#endif
