#ifndef __3941_PIN_DEF
#define __3941_PIN_DEF

#define DRIVE_FRONTLEFT 1
#define DRIVE_REARLEFT 2
#define DRIVE_FRONTRIGHT 3
#define DRIVE_REARRIGHT 4

#define PRESSURESWITCH_PIN 6
#define COMPRELAY_PIN 1

#define DRIVE_LEFTSHIFTSOLIN 1
#define DRIVE_LEFTSHIFTSOLOUT 2
#define DRIVE_RIGHTSHIFTSOLIN 3
#define DRIVE_RIGHTSHIFTSOLOUT 4

#define SHOOTER_WINCH_SPIKE 1
#define SHOOTER_WINCHDIGITALENCA 1
#define SHOOTER_WINCHDIGITALENCB 1
#define SHOOTER_WINCHMOTORSOLIN 1
#define SHOOTER_WINCHMOTORSOLOUT 1
#define SHOOTER_WINCHRATCHSOLIN 1
#define SHOOTER_WINCHRATCHSOLOUT 1
#define SHOOTER_WINDCHLIMITSWITCH 1
#define SHOOTER_ARMTALON 1
#define SHOOTER_ARMLIMITSWITCHBACK 1
#define SHOOTER_ARMLIMITSWITCHFRONT 1
#define SHOOTER_ARMPOT 1

#endif
